### ISSUE TITLE
unable to extract .split extension

### ISSUE THREAD

**Issue by vijayank88** [htfab/treepram-red#1]
Hello @htfab 
[user_project.gds.gz.00.split](https://github.com/htfab/treepram-red/blob/main/gds/user_project.gds.gz.00.split) 
I am unable extract `gds` files as extension with `.split`.
Can you please compress with valid extension as `.gz`?

**Comment by htfab** [comment]
Hello,
GitHub doesn't allow files larger than 100 MB. Even the compressed user_project.gds.gz was larger than this limit, so the Caravel framework has automatically split it up into two parts. You can either manually join the splits and then extract:
`cat user_project.gds.gz.*.split > user_project.gds.gz`
`gzip -d user_project.gds.gz`
Alternatively, if you have Caravel (e.g. if you cloned the repository recursively), you can run `make uncompress` in the repository root to join and extract all the compressed files.
